 Верстка модального окна продукта
Kabdoldinai/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-26 23:18 UTC by Kabdoldinai

1. Создала модальное окно, отцентрированное в центре страницы.
2. Добавила контент о продукте (картинки и информация: цена/цвета / размеры)
 3. Нанесла стили на элементы html

2021-09-27 04:02 UTC, BekStar7 commented
<img width="1172" alt="Снимок экрана 2021-09-27 в 07 38 58" src="https://user-images.githubusercontent.com/29562716/134843725-7b83964a-4fdd-49f6-9319-5cf733ac55f8.png">

2021-09-27 04:05 UTC, BekStar7 commented
![image](https://user-images.githubusercontent.com/29562716/134843868-72737d5a-f958-4c37-8b8b-0a64b3351063.png)

2021-09-27 04:08 UTC, BekStar7 commented
Не сделано:
- Отцентровано на странице по вертикали и горизонтали. По вертикале
- Высота не фиксированная и зависит от контента.
- Ширина фиксированная, но может меняться если отстуствет блок с фото.
- Предусмотреть правильную многострочность для фоток
- Добавить класс для “активной” превьюшки. (то что он появляется при нажатие, не считается)
- Количество опций может быть любым. Предусмотреть правильную многострочность.
- Реализовать функционал переключения опций через radio-buttons

2021-09-27 04:16 UTC, BekStar7 requested changes

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +
лишняя пустая строка

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +<head>
неверный табуляция

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +                    <img class="padding-for-icon" src="src/assets/close.svg" alt="close" width="18.67" height="18.67">
width 24px
height 24px

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +                                <h4>Твой баланс:</h4>
это не h4 =) Лучше p

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +                                    <p>S</p>
внутри label не нужен `p`

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +                        <h4>Детали:</h4>
`h3` или `p`

2021-09-27 04:16 UTC, BekStar7 commented on index.html
> +                        <h2>Как выбрать размер:</h2>
`h3` или `p`

2021-09-27 04:16 UTC, BekStar7 commented on src/css/style.css
> +    padding: 70px 0;
лишнее =)

2021-09-27 04:16 UTC, BekStar7 commented on src/css/style.css
> +    min-height: 588px;
это не нужно, height должен от контента делаться

2021-09-27 04:16 UTC, BekStar7 commented on src/css/style.css
> +    width: 96px;
лучше не задавать так, а чисто через отступы делать

2021-09-27 15:37 UTC, Kabdoldinai commented on index.html
> +
Вот тут едитор сам автоматически задает пустую строку ((

2021-09-27 18:20 UTC, Kabdoldinai commented on index.html
> +<head>
зашла в едитор, вроде все выровнила

2021-09-27 18:21 UTC, Kabdoldinai commented on index.html
> +                    <img class="padding-for-icon" src="src/assets/close.svg" alt="close" width="18.67" height="18.67">
исправила =)

2021-09-27 18:21 UTC, Kabdoldinai commented on index.html
> +                    <img class="padding-for-icon" src="src/assets/close.svg" alt="close" width="18.67" height="18.67">
но кнопка по прежнему немного выглядит большой

2021-09-27 18:22 UTC, Kabdoldinai commented on index.html
> +                                <h4>Твой баланс:</h4>
исправила на p

2021-09-27 18:22 UTC, Kabdoldinai commented on index.html
> +                                    <p>S</p>
исправила =)

2021-09-27 18:22 UTC, Kabdoldinai commented on index.html
> +                        <h4>Детали:</h4>
сделала h3

2021-09-27 18:23 UTC, Kabdoldinai commented on index.html
> +                        <h4>Детали:</h4>
кстати как вы определяете точно что нужно h3 / или p или р4,  я все таки еще немного путаюсь с хедарами.

2021-09-27 18:23 UTC, Kabdoldinai commented on index.html
> +                        <h2>Как выбрать размер:</h2>
исправила на h3

2021-09-27 18:23 UTC, Kabdoldinai commented on src/css/style.css
> +    padding: 70px 0;
убрала =)

2021-09-27 18:23 UTC, Kabdoldinai commented on src/css/style.css
> +    min-height: 588px;
убрала min-height

2021-09-27 18:26 UTC, Kabdoldinai commented on src/css/style.css
> +    width: 96px;
вроде подправила, так как немного меняла код, забыла этот момент =О

2021-09-27 18:28 UTC, Kabdoldinai commented on src/css/style.css
> +    width: 96px;
вроде подправила, так как немного меняла код, забыла этот момент =О

2021-09-28 03:34 UTC, BekStar7 commented on index.html
> +                        <h4>Детали:</h4>
https://convertmonster.ru/blog/seo-blog/html-tegi-h1-h2-h3-h4-h5-h6-zagolovki/
Семантика =)

2021-09-28 03:43 UTC, BekStar7 approved these changes

2021-09-28 03:46 UTC, merged